---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install nodejs
  sudo: yes
  apt: pkg=nodejs-legacy state=latest

- name: Install npm
  sudo: yes
  apt: pkg=npm state=latest

- name: Update npm
  npm: name=npm global=yes

- name: Install grunt
  npm: name=grunt-cli global=yes

- name: Install bower
  npm: name=bower global=yes

- name: Install ruby-sass
  sudo: yes
  apt: pkg=ruby-sass state=latest

- name: Install ruby
  sudo: yes
  apt: pkg=ruby state=latest

- name: Install sass
  gem: name=sass version=3.4.21 user_install=no
