---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Remove legacy Node
  sudo: yes
  apt: pkg=nodejs-legacy state=absent

- name: Remove legacy NPM
  sudo: yes
  apt: pkg=npm state=absent

- name: Allow installation of Node 4
  sudo: yes
  shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Install Node 4
  sudo: yes
  apt: pkg=nodejs state=latest

- name: Install grunt
  npm: name=grunt-cli global=yes

- name: Install bower
  npm: name=bower global=yes
